services:
  - type: web
    name: bot-aniversario-wpp
    runtime: node
    rootDir: wpp-api
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        value: https://dvvhecqfasrzursmgkxp.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: WPP_PORT
        value: 3000

  - type: web
    name: bot-aniversario
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2
    envVars:
      - key: SUPABASE_URL
        value: https://dvvhecqfasrzursmgkxp.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WPP_API_URL
        sync: false
